<h3><span class=" glyphicon glyphicon-tag"/>&nbspExceptionVerifier</h3><kbd>Verifies that exceptions are thrown during the test case execution</kbd><br><br><br><h4 style="margin:0px">Class: org.apache.aries.application.management.impl.AriesApplicationManagerImplTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testUpdateWithIncorrectDepMf() throws Exception {
  AriesApplication app=createApplication(TEST_EBA);
  DeploymentMetadata depMf=Skeleton.newMock(DeploymentMetadata.class);
  Skeleton.getSkeleton(depMf).setReturnValue(new MethodCall(DeploymentMetadata.class,"getApplicationSymbolicName"),"random.app");
  Skeleton.getSkeleton(depMf).setReturnValue(new MethodCall(DeploymentMetadata.class,"getApplicationVersion"),new Version("1.0.0"));
  AriesApplicationContextManager ctxMgr=Skeleton.newMock(AriesApplicationContextManager.class);
  _appMgr.setApplicationContextManager(ctxMgr);
  _appMgr.update(app,depMf);
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.application.runtime.itests.OBRResolverAdvancedTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ResolverException.class) public void testDemoAppResolveFail() throws ResolverException, Exception {
  System.setProperty(AppConstants.PROVISON_EXCLUDE_LOCAL_REPO_SYSPROP,"true");
  generateOBRRepoXML(false,TRANSITIVE_BUNDLE_BY_REFERENCE + ".jar",CORE_BUNDLE_BY_REFERENCE + "_0.0.0.jar",USE_BUNDLE_BY_REFERENCE + ".jar");
  RepositoryAdmin repositoryAdmin=context().getService(RepositoryAdmin.class);
  Repository[] repos=repositoryAdmin.listRepositories();
  for (  Repository repo : repos) {
    repositoryAdmin.removeRepository(repo.getURI());
  }
  repositoryAdmin.addRepository(new File("repository.xml").toURI().toURL());
  AriesApplicationManager manager=context().getService(AriesApplicationManager.class);
  AriesApplication app=manager.createApplication(FileSystem.getFSRoot(new File("demo.eba")));
  app=manager.resolve(app);
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ModellerException.class) public void testModellerException() throws Exception {
  ZipFixture bundle=ArchiveFixture.newJar().manifest().attribute(Constants.BUNDLE_SYMBOLICNAME,CORE_BUNDLE_BY_VALUE).attribute(Constants.BUNDLE_MANIFESTVERSION,"2").attribute(Constants.IMPORT_PACKAGE,"a.b.c, p.q.r, x.y.z, javax.naming").attribute(Constants.BUNDLE_VERSION,"1.0.0").end();
  FileOutputStream fout=new FileOutputStream("delete.jar");
  bundle.writeOut(fout);
  fout.close();
  generateOBRRepoXML(false,"delete.jar");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.application.runtime.itests.OBRResolverTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Test the resolution should fail because the required package org.apache.aries.util is provided by the local runtime,
 * which is not included when provisioning.
 * @throws Exception
 */
@Test(expected=ResolverException.class) public void testProvisionExcludeLocalRepo() throws Exception {
  System.setProperty(AppConstants.PROVISON_EXCLUDE_LOCAL_REPO_SYSPROP,"true");
  generateOBRRepoXML(TRANSITIVE_BUNDLE_BY_REFERENCE + ".jar",CORE_BUNDLE_BY_REFERENCE + ".jar");
  RepositoryAdmin repositoryAdmin=context().getService(RepositoryAdmin.class);
  Repository[] repos=repositoryAdmin.listRepositories();
  for (  Repository repo : repos) {
    repositoryAdmin.removeRepository(repo.getURI());
  }
  repositoryAdmin.addRepository(new File("repository.xml").toURI().toURL());
  AriesApplicationManager manager=context().getService(AriesApplicationManager.class);
  AriesApplication app=manager.createApplication(FileSystem.getFSRoot(new File("blog.eba")));
  app=manager.resolve(app);
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ResolverException.class) public void test_resolve_non_self_contained_app_in_isolation() throws Exception {
  createAndResolveSelfContainedApp("org.osgi.service.blueprint");
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ResolverException.class) public void testBlogAppResolveFail() throws ResolverException, Exception {
  System.setProperty(AppConstants.PROVISON_EXCLUDE_LOCAL_REPO_SYSPROP,"false");
  generateOBRRepoXML(TRANSITIVE_BUNDLE_BY_REFERENCE + ".jar",CORE_BUNDLE_BY_REFERENCE + "_0.0.0.jar");
  RepositoryAdmin repositoryAdmin=context().getService(RepositoryAdmin.class);
  Repository[] repos=repositoryAdmin.listRepositories();
  for (  Repository repo : repos) {
    repositoryAdmin.removeRepository(repo.getURI());
  }
  repositoryAdmin.addRepository(new File("repository.xml").toURI().toURL());
  AriesApplicationManager manager=context().getService(AriesApplicationManager.class);
  AriesApplication app=manager.createApplication(FileSystem.getFSRoot(new File("blog.eba")));
  app=manager.resolve(app);
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.blueprint.itests.authz.AuthorizationTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=AccessControlException.class) public void testOnlyAdminDenied() throws LoginException, BundleException {
  JAASHelper.doAs(new String[]{"user"},new CallOnlyAdmin());
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=AccessControlException.class) public void testUserAdndAdminDeniedForUnauthenticated() throws LoginException, BundleException {
  service.userAndAdmin("Hi");
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=AccessControlException.class) public void testDenyAll() throws LoginException, BundleException {
  JAASHelper.doAs(new String[]{"admin"},new CallNoOne());
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.blueprint.plugin.model.BeanTest </h4><pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testMultipleDestroyMethods(){
  new Bean(BadBean2.class);
}

</code></pre>

<br>
<pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testMultipleInitMethods(){
  new Bean(BadBean1.class);
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=UnsupportedOperationException.class) public void testBadFieldBean1(){
  new Context(BadFieldBean1.class).resolve();
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=UnsupportedOperationException.class) public void testBadFieldBean3(){
  new Context(BadFieldBean3.class).resolve();
}

</code></pre>

<br>
<pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=UnsupportedOperationException.class) public void testSpringNestedTransactionNotSupported(){
  new Bean(BadBean3.class);
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=UnsupportedOperationException.class) public void testBadFieldBean2(){
  new Context(BadFieldBean2.class).resolve();
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.blueprint.proxy.WovenProxyGeneratorTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=NoSuchFieldException.class) public void testNonSerializableClassHasNoGeneratedSerialVersionUID() throws Exception {
  Class<?> woven=getProxyClass(getTestClass());
  woven.getDeclaredField("serialVersionUID");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.blueprint.proxy.WovenProxyPlusSubclassGeneratorTest </h4><pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=NoSuchFieldException.class) public void testGeneratedSVUIDisSynthetic() throws Exception {
  super.testGeneratedSVUIDisSynthetic();
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.blueprint.utils.ReflectionUtilsTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ComponentDefinitionException.class) public void testMultipleSettersMatchByType() throws Exception {
  loadProps(MultipleMatchesByType.class,false);
  sut[1].set(new MultipleMatchesByType(),new LinkedList<String>(),mockBlueprint);
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ComponentDefinitionException.class) public void testMultipleMatchesByConversion() throws Exception {
  loadProps(MultipleMatchesByConversion.class,false);
  sut[1].set(new MultipleMatchesByConversion(),new HashSet<String>(),mockBlueprint);
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ComponentDefinitionException.class) public void testApplicableSetter() throws Exception {
  loadProps(OverloadedSetters.class,false);
  sut[1].set(new OverloadedSetters(),new Inconvertible(),mockBlueprint);
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.ejb.modelling.impl.EJBLocatorTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ModellerException.class) public void testUnavailable() throws ModellerException {
  new EJBLocationUnavailable().findEJBs(null,null,null);
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.jndi.InitialContextTest </h4><pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=NoInitialContextException.class) public void testLookupWithoutICF() throws NamingException {
  Properties props=new Properties();
  props.put(JNDIConstants.BUNDLE_CONTEXT,bc);
  InitialContext ctx=new InitialContext(props);
  ctx.lookup("/");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.jndi.url.BlueprintURLContextTest </h4><pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
/** 
 * Check that we get a NameNotFoundException if we lookup something not in the
 * registry.
 * @throws NamingException
 */
@Test(expected=NameNotFoundException.class) public void testLookupForServiceWeNeverHad() throws NamingException {
  InitialContext ctx=new InitialContext();
  ctx.lookup("blueprint:comp/this.is.not.a.component");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.jndi.url.OsgiNameParserTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Make sure it fails if we try to parse something that isn't in aries:services
 * @throws NamingException
 */
@Test(expected=InvalidNameException.class) public void checkOutsideNamespace() throws NamingException {
  checkName("java","comp","env","jms","cf");
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=InvalidNameException.class) public void checkIncorrectPath() throws NamingException {
  checkName("osgi","services","java.lang.Runnable");
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=InvalidNameException.class) public void checkIllegalPath() throws NamingException {
  checkName("osgi","wibble","java.lang.Runnable");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.jndi.url.ServiceRegistryContextTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Check that we get a NameNotFoundException if we lookup something not in the
 * registry.
 * @throws NamingException
 */
@Test(expected=NameNotFoundException.class) public void testLookupForServiceWeNeverHad() throws NamingException {
  BundleMock mock=new BundleMock("scooby.doo",new Properties());
  Thread.currentThread().setContextClassLoader(mock.getClassLoader());
  InitialContext ctx=new InitialContext();
  ctx.lookup("osgi:service/java.lang.Integer");
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ServiceException.class) public void checkProxyWhenServiceGoes() throws ServiceException, NamingException {
  BundleMock mock=new BundleMock("scooby.doo",new Properties());
  Thread.currentThread().setContextClassLoader(mock.getClassLoader());
  InitialContext ctx=new InitialContext();
  Runnable r=(Runnable)ctx.lookup("osgi:service/java.lang.Runnable");
  r.run();
  Skeleton.getSkeleton(service).assertCalled(new MethodCall(Runnable.class,"run"));
  reg.unregister();
  r.run();
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Check that we get a NameNotFoundException if we lookup after the service
 * has been unregistered.
 * @throws NamingException
 */
@Test(expected=NameNotFoundException.class) public void testLookupWhenServiceHasBeenRemoved() throws NamingException {
  reg.unregister();
  BundleMock mock=new BundleMock("scooby.doo",new Properties());
  Thread.currentThread().setContextClassLoader(mock.getClassLoader());
  InitialContext ctx=new InitialContext();
  ctx.lookup("osgi:service/java.lang.Runnable");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.jpa.container.itest.EclipseAdditionalTest </h4><pre class="type-5 type-10 type-2 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies (un)successful execution of the test case by reporting explicitly a failure">UtilityVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Contains more than 2 JUnit-based stereotypes">HybridVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies (un)successful execution of the test case by reporting explicitly a failure
- Verifies that exceptions are thrown during the test case execution
- Contains more than 2 JUnit-based stereotypes
"></span><br>
@Test(expected=IllegalStateException.class) public void testEntityManagerFactoryWithIncompletePersistenceUnit() throws Exception {
  getService(EntityManagerFactory.class,"(osgi.unit.name=incompleteTestUnit)",1000);
  Assert.fail("There should be no EntityManagerFactory registered since this persistence unit is incomplete");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.jpa.support.osgi.impl.EmfTrackerTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=PersistenceException.class) public void testOriginalExceptionThrown(){
  EmSupplier emSupplier=mock(EmSupplier.class);
  EntityManager em=mock(EntityManager.class);
  when(emSupplier.get()).thenReturn(em);
  doThrow(new PersistenceException("Message")).when(em).flush();
  EntityManager emProxy=EMFTracker.createProxy(emSupplier);
  emProxy.flush();
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.proxy.itests.AbstractWeavingProxyTest </h4><pre class="type-12 type-5 type-10 type-2 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies assertions inside branch conditions">BranchVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies (un)successful execution of the test case by reporting explicitly a failure">UtilityVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Contains more than 2 JUnit-based stereotypes">HybridVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies assertions inside branch conditions
- Verifies (un)successful execution of the test case by reporting explicitly a failure
- Verifies that exceptions are thrown during the test case execution
- Contains more than 2 JUnit-based stereotypes
"></span><br>
@Test(expected=FinalModifierException.class) public void checkProxyController() throws Exception {
  context().registerService(ProxyWeavingController.class.getName(),new ProxyWeavingController(){
    public boolean shouldWeave(    WovenClass arg0,    WeavingHelper arg1){
      return false;
    }
  }
,null);
  Bundle b=bundleContext.getBundle();
  Callable c=new TestCallable();
  Collection<Class<?>> classes=new ArrayList<Class<?>>();
  Callable<?> callable=new TestFinalDelegate();
  classes.add(callable.getClass());
  Object o=mgr.createDelegatingProxy(b,classes,c,callable);
  if (o instanceof WovenProxy)   fail("Proxy should not have been woven!");
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.transaction.ComponentTxDataTest </h4><pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testNoPrivateAnnotation(){
  new ComponentTxData(BadlyAnnotatedPojo1.class);
}

</code></pre>

<br>
<pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testNoStaticAnnotation(){
  new ComponentTxData(BadlyAnnotatedPojo1.class);
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.util.BundleToClassLoaderAdapterTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ClassNotFoundException.class) public void testInheritance() throws Exception {
  ClassLoader testLoader=new ClassLoader(makeSUT(false)){
  }
;
  testLoader.loadClass(Bundle.class.getName());
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=ClassNotFoundException.class) public void testLoadClassFailure() throws Exception {
  makeSUT(false).loadClass(Bundle.class.getName());
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.util.RecursiveBundleTrackerTest </h4><pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testMissingStarting(){
  new RecursiveBundleTracker(null,Bundle.INSTALLED | Bundle.RESOLVED | Bundle.ACTIVE| Bundle.STOPPING,null);
}

</code></pre>

<br>
<pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testMissingInstalled(){
  new RecursiveBundleTracker(null,Bundle.RESOLVED | Bundle.STARTING | Bundle.ACTIVE| Bundle.STOPPING,null);
}

</code></pre>

<br>
<pre class="type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
"></span><br>
@Test(expected=IllegalArgumentException.class) public void testMissingStopping(){
  new RecursiveBundleTracker(null,Bundle.INSTALLED | Bundle.RESOLVED | Bundle.STARTING| Bundle.ACTIVE,null);
}

</code></pre>

<br>
<h4 style="margin:0px">Class: org.apache.aries.util.filesystem.FileSystemTest </h4><pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Make sure we correctly understand the content of the application when the
 * application is a zip. This test just checks that the
 * root directory returns the expected information.
 * @throws IOException
 */
@Test(expected=UnsupportedOperationException.class) public void basicRootDirTestsWithZip() throws IOException {
  File baseDir=new File("fileSystemTest/app2.zip");
  IDirectory dir=FileSystem.getFSRoot(baseDir);
  runBasicRootDirTests(dir,baseDir.length(),baseDir.lastModified());
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Make sure we correctly understand the content of the application when the
 * application is an exploded directory. This test just checks that the
 * root directory returns the expected information.
 * @throws IOException
 */
@Test(expected=UnsupportedOperationException.class) public void basicRootDirTestsWithFiles() throws IOException {
  File baseDir=new File(getTestResourceDir(),"/app1");
  File manifest=new File(baseDir,"META-INF/APPLICATION.MF");
  IDirectory dir=FileSystem.getFSRoot(baseDir);
  runBasicRootDirTests(dir,baseDir.length(),manifest.lastModified());
}

</code></pre>

<br>
<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Make sure we correctly understand the content of the application when the
 * application is a zip. This test just checks that the
 * root directory returns the expected information.
 * @throws IOException
 */
@Test(expected=UnsupportedOperationException.class) public void basicRootDirTestsWithZipInputStream() throws IOException {
  File baseDir=new File("fileSystemTest/app2.zip");
  ICloseableDirectory dir=FileSystem.getFSRoot(new FileInputStream(baseDir));
  try {
    runBasicRootDirTests(dir,baseDir.length(),baseDir.lastModified());
  }
  finally {
    dir.close();
  }
}

</code></pre>

<br>
<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
