<h3><span class=" glyphicon glyphicon-tag"/>&nbspLogger</h3><kbd>Invokes logging operations</kbd><br><br><br><h4 style="margin:0px">Class: org.apache.commons.exec.issues.Exec49Test </h4><pre class="type-15 type-9 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Invokes logging operations">Logger</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Invokes logging operations
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * The issue was detected when trying to capture stdout/stderr with a PipedOutputStream and
 * then pass that to a PipedInputStream. The following code will produce the error.
 * The reason for the error is the PipedOutputStream is not being closed correctly,
 * causing the PipedInputStream to break.
 * @throws Exception the test failed
 */
@Test public void testExec49_1() throws Exception {
  if (OS.isFamilyUnix()) {
    final CommandLine cl=CommandLine.parse("/bin/ls");
    cl.addArgument("/opt");
    final PipedOutputStream pipedOutputStream=new PipedOutputStream();
    final PumpStreamHandler psh=new PumpStreamHandler(pipedOutputStream);
    exec.setStreamHandler(psh);
    System.out.println("Preparing to execute process - commandLine=" + cl.toString());
    final DefaultExecuteResultHandler handler=new DefaultExecuteResultHandler();
    exec.execute(cl,handler);
    System.out.println("Process spun off successfully - process=" + cl.getExecutable());
    int x;
    final PipedInputStream pis=new PipedInputStream(pipedOutputStream);
    while ((x=pis.read()) >= 0) {
    }
    pis.close();
    handler.waitFor(10000);
    handler.getExitValue();
  }
}

</code></pre>

<br>
<pre class="type-15 type-9 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Invokes logging operations">Logger</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Invokes logging operations
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * The issue was detected when trying to capture stdout with a PipedOutputStream and
 * then pass that to a PipedInputStream. The following code will produce the error.
 * The reason for the error is the PipedOutputStream is not being closed correctly,
 * causing the PipedInputStream to break.
 * @throws Exception the test failed
 */
@Test public void testExec49_2() throws Exception {
  if (OS.isFamilyUnix()) {
    final CommandLine cl=CommandLine.parse("/bin/ls");
    cl.addArgument("/opt");
    final PipedOutputStream pipedOutputStream=new PipedOutputStream();
    final PumpStreamHandler psh=new PumpStreamHandler(pipedOutputStream,new ByteArrayOutputStream());
    exec.setStreamHandler(psh);
    System.out.println("Preparing to execute process - commandLine=" + cl.toString());
    final DefaultExecuteResultHandler handler=new DefaultExecuteResultHandler();
    exec.execute(cl,handler);
    System.out.println("Process spun off successfully - process=" + cl.getExecutable());
    int x;
    final PipedInputStream pis=new PipedInputStream(pipedOutputStream);
    while ((x=pis.read()) >= 0) {
    }
    pis.close();
    handler.waitFor(10000);
    handler.getExitValue();
  }
}

</code></pre>

<br>
<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
