<h3 style="margin:0px">Class: org.apache.aries.jndi.url.OsgiNameParserTest (4 methods) </h3><br><pre style="padding:0"><code class="html"><div id="tags"><button id="11"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('11')" data-toggle="tooltip" title="Executes methods or other tests from the same test unit"><kbd id="tag-11"class="label-info"style="display: inline-block;font-size:7pt" >ExecutionTester&nbsp;(4)</kbd></button>&nbsp;<button id="10"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('10')" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution"><kbd id="tag-10"class="label-info"style="display: inline-block;font-size:7pt" >ExceptionVerifier&nbsp;(3)</kbd></button>&nbsp;</div></code></pre><center><button onclick="showBlocks()" style="margin:6px">Update filter <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> </button></center><br>
<pre class="type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * OK, so we check that we can call checkNames multiple times.
 * @throws NamingException
 */
@Test public void checkValidNames() throws NamingException {
  checkName("aries","services","java.lang.Runnable","(a=b)");
  checkName("aries","services","java.lang.Runnable");
  checkName("osgi","service","java.lang.Runnable");
  checkName("osgi","service","java.lang.Runnable","(a=b)");
  checkName("osgi","servicelist","java.lang.Runnable");
  checkName("osgi","servicelist","java.lang.Runnable","(a=b)");
  checkName("osgi","servicelist","jdbc","grok","DataSource");
  checkName("osgi","framework","bundleContext");
  checkName("osgi","service","javax.sql.DataSource","(osgi.jndi.servicee.name=jdbc/myDataSource)");
  checkName("osgi","service","javax.sql.DataSource","(&(a=/b)(c=/d))");
  checkName("osgi","service");
}

</code></pre>

<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
/** 
 * Make sure it fails if we try to parse something that isn't in aries:services
 * @throws NamingException
 */
@Test(expected=InvalidNameException.class) public void checkOutsideNamespace() throws NamingException {
  checkName("java","comp","env","jms","cf");
}

</code></pre>

<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=InvalidNameException.class) public void checkIncorrectPath() throws NamingException {
  checkName("osgi","services","java.lang.Runnable");
}

</code></pre>

<pre class="type-10 type-11 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expected=InvalidNameException.class) public void checkIllegalPath() throws NamingException {
  checkName("osgi","wibble","java.lang.Runnable");
}

</code></pre>

<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
