<h3 style="margin:0px">Class: org.jclouds.fallbacks.HeaderToRetryAfterExceptionTest (4 methods) </h3><br><pre style="padding:0"><code class="html"><div id="tags"><button id="10"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('10')" data-toggle="tooltip" title="Executes methods or other tests from the same test unit"><kbd id="tag-10"class="label-info"style="display: inline-block;font-size:7pt" >ExecutionTester&nbsp;(4)</kbd></button>&nbsp;<button id="3"style="border-width:0;padding:0;background:#282B2E"  onclick="filter('3')" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution"><kbd id="tag-3"class="label-info"style="display: inline-block;font-size:7pt" >ExceptionVerifier&nbsp;(4)</kbd></button>&nbsp;</div></code></pre><center><button onclick="showBlocks()" style="margin:6px">Update filter <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> </button></center><br>
<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=RuntimeException.class) public void testArbitraryExceptionDoesntConvert() throws Exception {
  fn.createOrPropagate(new RuntimeException());
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=RetryAfterException.class,expectedExceptionsMessageRegExp="retry in 86400 seconds") public void testHttpResponseExceptionWithRetryAfterPastIsZero() throws Exception {
  fn.createOrPropagate(new HttpResponseException(command,HttpResponse.builder().statusCode(503).addHeader(HttpHeaders.RETRY_AFTER,"Sun, 2 Jan 2000 00:00:00 GMT").build()));
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=RetryAfterException.class,expectedExceptionsMessageRegExp="retry now") public void testHttpResponseExceptionWithRetryAfterDate() throws Exception {
  fn.createOrPropagate(new HttpResponseException(command,HttpResponse.builder().statusCode(503).addHeader(HttpHeaders.RETRY_AFTER,"Fri, 31 Dec 1999 23:59:59 GMT").build()));
}

</code></pre>

<pre class="type-3 type-10 "><code><span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Verifies that exceptions are thrown during the test case execution">ExceptionVerifier</span>&nbsp;<span class="label label-info" style="display: inline-block;" data-toggle="tooltip" title="Executes methods or other tests from the same test unit">ExecutionTester</span>&nbsp;<span class=" glyphicon glyphicon-comment" aria-hidden="true" label-info" data-toggle="tooltip" title="This method/test case: 
- Verifies that exceptions are thrown during the test case execution
- Executes methods or other tests from the same test unit
"></span><br>
@Test(expectedExceptions=RetryAfterException.class,expectedExceptionsMessageRegExp="retry in 700 seconds") public void testHttpResponseExceptionWithRetryAfterOffset() throws Exception {
  fn.createOrPropagate(new HttpResponseException(command,HttpResponse.builder().statusCode(503).addHeader(HttpHeaders.RETRY_AFTER,"700").build()));
}

</code></pre>

<script>$(document).ready(function() {
  $('pre code').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});</script>
